export const userProfile = {
  active: 3,
  websiteUrl: ' rachemorrison.com',
  linkedinUrl: 'linkedin.com',
  twitterUrl: 'twtitter.com',
  githubUrl: 'github.com',
  dribbbleUrl: 'dribble.com',
  avatarUrl: 'https://cdn.filestackcontent.com/Ezde37fATDer1ICQJNrR',
  bio: 'I’ve previously worked on cloud computing products at Google in San Francisco. I recently relocated to Boulder and am open to remote roles and in-person in Boulder/Denver.',
  firstName: 'Rachel',
  id: 416,
  lastName: 'Morrison',
  resumeUrl:
    'https://internal.sandbox1.getro.com/files?path=sandbox%2F1-NextJS+AWS+Pattern.pdf',
  verified: false,
  email: 'email@gmail.com',
  jobFunctions: [],
  locations: [],
  currentLocation: { name: 'Toronto Ontario, CA' },
  skills: [
    { value: 2205, name: 'Software Engineering' },
    { value: 2206, name: 'Agile Software Development' },
    { value: 2207, name: 'Javascript' },
  ],
  referralsReceived: [
    {
      id: 374,
      createdAt: '2021-12-08T14:32:38.056Z',
      relationshipLevel: 1,
      relationshipText:
        'this is to test how a vouch will be displayed in the new FE of platform',
      recommendationText: null,
      voucher: {
        id: 1,
        firstName: 'Sol',
        email: 'mystic@example.com',
        lastName: 'Trantow',
        linkedinUrl: 'https://linkedin.com/in/cum',
        avatarUrl: 'https://cdn.filepicker.io/api/file/kbvHK1paSqHLkLJLSHOV',
        bio: 'Suscipit dolorum fugit. Dolore cum expedita. Esse velit aut. Et tempore qui. Minima ut consequatur.',
        verified: true,
      },
    },
    {
      id: 375,
      score: 2,
      createdAt: '2021-12-08T14:32:38.056Z',
      relationshipLevel: 2,
      relationshipText:
        "Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be?",
      recommendationText: null,
      voucher: {
        id: 1,
        firstName: 'Test',
        email: 'test@user.com',
        lastName: 'User',
        linkedinUrl: 'https://linkedin.com/in/cum',
        avatarUrl: 'https://cdn.filestackcontent.com/xtmH1YSCqFSZBZAWxzAK',
        bio: 'Suscipit dolorum fugit. Dolore cum expedita. Esse velit aut. Et tempore qui. Minima ut consequatur.',
        verified: false,
      },
    },
    {
      id: 376,
      createdAt: '2021-12-08T14:32:38.056Z',
      relationshipLevel: 3,
      relationshipText:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
      recommendationText: null,
      voucher: {
        id: 1,
        firstName: 'No',
        email: 'test@user.com',
        lastName: 'Face',
        linkedinUrl: 'https://linkedin.com/in/cum',
        avatarUrl: '',
        bio: 'Suscipit dolorum fugit. Dolore cum expedita. Esse velit aut. Et tempore qui. Minima ut consequatur.',
        verified: true,
      },
    },
  ],
  referralsGiven: [],
  resumeName: 'NextJS AWS Pattern.pdf',
  mentorship: 'no',
  jobSearchStatus: 'not_looking',
  jobSearchStage: 'Not looking',
  employmentTypes: [],
  jobFunctionIds: [],
  willWorkAnywhere: 'no',
  remoteWork: 'no',
  opportunities: 'no',
  seniority: { title: 'Unspecified', description: '' },
  userTalentCollection: {
    id: 2,
    userId: 1,
    collectionId: 2,
    status: 'pending',
    approvedAt: null,
    approvedBy: null,
    createdAt: '2020-12-18T13:59:32.356Z',
    updatedAt: '2021-05-13T14:36:00.279Z',
    declinedBy: null,
    declinedAt: null,
    coverLetter: null,
    sharePermission: true,
    vouchesCount: 0,
    questionnaire: null,
    approvedByCollection: false,
    source: 'undefined',
    onboardingReminderSentAt: null,
    invitedBy: null,
    verifiedBy: null,
    invitationReminderSentAt: null,
    verifiedAt: '2020-11-18T13:59:32.306Z',
    visibility: { label: 'Visible to companies', value: 'visible' },
    userDeleted: false,
    isCompanyAdmin: true,
    isNetworkAdmin: true,
    isNetworkAmbassador: false,
    hideFromDomains: [],
    hideFromCompanies: [],
  },
};
