name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint:JS
        run: yarn lint:js
      - name: Run Jest
        run: yarn test:ci
      - name: Test build
        run: yarn build-storybook
